name: kokoro-fastapi-cpu
services:
  kokoro-tts:
    build:
      context: ../..
      dockerfile: docker/cpu/Dockerfile
    volumes:
      - ../../api:/app/api
    command: ["uv", "run", "--extra", "cpu", "--no-sync", "python", "-m", "uvicorn", "api.src.main:app", "--host", "0.0.0.0", "--port", "8880", "--loop", "uvloop", "--http", "httptools", "--no-access-log", "--log-level", "info"]
    ports:
      - "8880:8880"
    environment:
      - PYTHONPATH=/app:/app/api
      - USE_GPU=false
      - DEFAULT_RESPONSE_FORMAT=pcm
      - DEFAULT_STREAM=true
      - GPU_INFERENCE_CONCURRENCY=2
      - GPU_INFERENCE_WORKERS=2
      - API_LOG_LEVEL=INFO
      - UVICORN_LOG_LEVEL=info
      - TEMP_FILE_DIR=/tmp/kokoro_temp_files
      
  # # Gradio UI service [Comment out everything below if you don't need it]
  # gradio-ui:
  #   image: ghcr.io/remsky/kokoro-fastapi-ui:v${VERSION}
  #   # Uncomment below (and comment out above) to build from source instead of using the released image
  #   build:
  #     context: ../../ui
  #   ports:
  #     - "7860:7860"
  #   volumes:
  #     - ../../ui/data:/app/ui/data
  #     - ../../ui/app.py:/app/app.py  # Mount app.py for hot reload
  #   environment:
  #     - GRADIO_WATCH=True  # Enable hot reloading
  #     - PYTHONUNBUFFERED=1  # Ensure Python output is not buffered
  #     - DISABLE_LOCAL_SAVING=false  # Set to 'true' to disable local saving and hide file view
  #     - API_HOST=kokoro-tts  # Set TTS service URL
  #     - API_PORT=8880  # Set TTS service PORT
